# ASSIGNMENT:  BINARY-CLASS CLASSIFICATION :
### SONAR- ROCK VS MINE 
<br> <br>

<img src = "https://www.researchgate.net/profile/Paven_Mathew/publication/325895659/figure/fig1/AS:716081412988932@1547738521477/Figure-Application-of-SONAR-in-ships.jpg" width="200" align="left">

<img src="https://ak.picdn.net/shutterstock/videos/3633083/thumb/1.jpg?ip=x480" width="350" >

<br> 

###### Purpose :
To predict the underwater **ROCK or Explosive MINE** .
###### Description :
The dataset contains a set of 208 records under 60 attributes - Data consist of sonar signals either bounced off a metal cylinder or bounced off a roughly cylindrical rock and Class(R - Rock , M - Mine).


### STEP 1 : Load all the necessary libraries 

In [ ]:
<img src = "https://www.researchgate.net/profile/Paven_Mathew/publication/325895659/figure/fig1/AS:716081412988932@1547738521477/Figure-Application-of-SONAR-in-ships.jpg" width="200">

In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](http://networkrepository.com/sonar.php) shuffling ,spliting in **Train** and **Test** sets with 90% - 40% ratio to one-hot-encoding on labels . 


In [19]:
df = pd.read_csv('sonar.csv')

In [31]:
pd.set_option('display.max_rows',None)

In [30]:
pd.set_option('display.max_columns',None)

In [24]:
len(df[df['R']=='M'])

111

In [25]:
len(df[df['R']=='R'])

96

In [26]:
gf = df.sample(frac=1)

In [28]:
sonar = gf.values

In [89]:
x_train = sonar[:125,:60].astype('float')
x_train.shape

(125, 60)

In [68]:
y_train = sonar[:125,60]
len(y_train)

125

In [58]:
x_test = sonar[124:,:60].astype('float')
x_test.shape

(83, 60)

In [57]:
y_test = sonar[124:,60]
y_test.shape

(83,)

In [76]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_y = le.fit_transform(y_train)
encoded_y

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0])

M - 0
 R - 1

In [78]:
encoded_y_train = tf.keras.utils.to_categorical(encoded_y)
encoded_y_train

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [86]:
encoded_y = le.fit_transform(y_test)
encoded_y_test = tf.keras.utils.to_categorical(encoded_y)

### STEP 3 : Model Architecture 
**Note:**
* Select input shape , Activation Function and Output Nodes wisely.

In [83]:
from tensorflow.keras import layers
from tensorflow.keras import models

In [234]:
model = models.Sequential()

In [235]:
model.add(layers.Dense(50,activation='relu',input_shape=(60,)))
model.add(layers.Dense(40,activation='relu'))
model.add(layers.Dense(2,activation='sigmoid'))

### STEP 4 : Compilation Step 

**Note:**

* Use loss function that is designed for binary classification i.e **binary_crossentropy**

In [236]:
model.compile(optimizer='adam',loss = 'binary_crossentropy', metrics = ['accuracy'])

In [237]:
model.fit(x_train,encoded_y_train,epochs=101)

Epoch 1/101
4/4 [==============================] - 0s 1ms/step - loss: 0.7048 - accuracy: 0.4800
Epoch 2/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6907 - accuracy: 0.5360
Epoch 3/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6846 - accuracy: 0.5440
Epoch 4/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6815 - accuracy: 0.5680
Epoch 5/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6776 - accuracy: 0.5760
Epoch 6/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6745 - accuracy: 0.6000
Epoch 7/101
4/4 [==============================] - 0s 3ms/step - loss: 0.6705 - accuracy: 0.6240
Epoch 8/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6665 - accuracy: 0.6480
Epoch 9/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6623 - accuracy: 0.6640
Epoch 10/101
4/4 [==============================] - 0s 2ms/step - loss: 0.6569 - accuracy: 0.6640
Epoch 11/101
4/4 [===========

4/4 [==============================] - 0s 2ms/step - loss: 0.1901 - accuracy: 0.9600
Epoch 85/101
4/4 [==============================] - 0s 2ms/step - loss: 0.1871 - accuracy: 0.9520
Epoch 86/101
4/4 [==============================] - 0s 1ms/step - loss: 0.1858 - accuracy: 0.9520
Epoch 87/101
4/4 [==============================] - 0s 2ms/step - loss: 0.1807 - accuracy: 0.9600
Epoch 88/101
4/4 [==============================] - 0s 2ms/step - loss: 0.1803 - accuracy: 0.9600
Epoch 89/101
4/4 [==============================] - 0s 2ms/step - loss: 0.1802 - accuracy: 0.9600
Epoch 90/101
4/4 [==============================] - 0s 1ms/step - loss: 0.1816 - accuracy: 0.9520
Epoch 91/101
4/4 [==============================] - 0s 1ms/step - loss: 0.1715 - accuracy: 0.9600
Epoch 92/101
4/4 [==============================] - 0s 1ms/step - loss: 0.1750 - accuracy: 0.9600
Epoch 93/101
4/4 [==============================] - 0s 2ms/step - loss: 0.1674 - accuracy: 0.9680
Epoch 94/101
4/4 [===============

### STEP 5 : Evaluation 

In [238]:
model.evaluate(x_test,encoded_y_test)

3/3 [==============================] - 0s 2ms/step - loss: 0.5085 - accuracy: 0.8072


[0.5085119009017944, 0.8072289228439331]

### STEP 6 : Prediction 

In [294]:
i = 80
predict = model.predict(x_test[i].reshape(1,60))

In [295]:
predict

array([[0.4887347 , 0.51253605]], dtype=float32)

In [296]:
count = 0
if predict[0][1] > 0.50:
    print("R")
    count +=1
else:
    print('M')

R


In [298]:
print("actual data=",x_test[i],"actual label is ",y_test[i])
print("the is data",x_test[i],"predicted is",'R' if predict[0][1] > 0.50 else 'M' )

actual data= [2.010e-02 1.160e-02 1.230e-02 2.450e-02 5.470e-02 2.080e-02 8.910e-02
 8.360e-02 1.335e-01 1.199e-01 1.742e-01 1.387e-01 2.042e-01 2.580e-01
 2.616e-01 2.097e-01 2.532e-01 3.213e-01 4.327e-01 4.760e-01 5.328e-01
 6.057e-01 6.696e-01 7.476e-01 8.930e-01 9.405e-01 1.000e+00 9.785e-01
 8.473e-01 7.639e-01 6.701e-01 4.989e-01 3.718e-01 2.196e-01 1.416e-01
 2.680e-01 2.630e-01 3.104e-01 3.392e-01 2.123e-01 1.170e-01 2.655e-01
 2.203e-01 1.541e-01 1.464e-01 1.044e-01 1.225e-01 7.450e-02 4.900e-02
 2.240e-02 3.200e-03 7.600e-03 4.500e-03 5.600e-03 7.500e-03 3.700e-03
 4.500e-03 2.900e-03 8.000e-04 1.800e-03] actual label is  R
the is data [2.010e-02 1.160e-02 1.230e-02 2.450e-02 5.470e-02 2.080e-02 8.910e-02
 8.360e-02 1.335e-01 1.199e-01 1.742e-01 1.387e-01 2.042e-01 2.580e-01
 2.616e-01 2.097e-01 2.532e-01 3.213e-01 4.327e-01 4.760e-01 5.328e-01
 6.057e-01 6.696e-01 7.476e-01 8.930e-01 9.405e-01 1.000e+00 9.785e-01
 8.473e-01 7.639e-01 6.701e-01 4.989e-01 3.718e-01 2.196e-01 1